breaking up nginx config files

diff --git a/conf/deploy.bash.j2 b/conf/deploy.bash.j2
--- a/conf/deploy.bash.j2
+++ b/conf/deploy.bash.j2
@@ -31,18 +31,39 @@ if [[ ! -e instance/env.sh ]]; then
     chmod +x instance/env.sh
 fi
 
-# Check the nginx config file #################################################
-if [[ ! -e {{nginx_file_path}} ]] || [[ `diff _build/invoicer.nginx {{nginx_file_path}}` ]]; then
-    echo "deploying nginx config"
+# Check the nginx config files ################################################
+if [[ ! -e {{nginx_upstream_file_path}} ]] || [[ `diff _build/invoicer-upstream.nginx {{nginx_upstream_file_path}}` ]]; then
+    echo "deploying nginx upstream config"
 
-    if [[ -e {{nginx_file_path}} ]]; then
+    if [[ -e {{nginx_upstream_file_path}} ]]; then
         # Make a backup of the existing file.  This works because nginx only
         # looks for ".conf" files.
         today=`date +%Y-%m-%d-%H:%M:%S`
-        mv {{nginx_file_path}} {{nginx_file_path}}.$today
+        mv {{nginx_upstream_file_path}} {{nginx_upstream_file_path}}.$today
     fi
 
-    cp _build/invoicer.nginx {{nginx_file_path}}
+    cp _build/invoicer-upstream.nginx {{nginx_upstream_file_path}}
+
+    $(nginx -t > /dev/null 2>&1)
+    if [[ ! "$?" -eq 0 ]]; then
+        echo "nginx config file test failed!"
+        exit 1
+    fi
+
+    systemctl restart nginx.service
+fi
+
+if [[ ! -e {{nginx_location_file_path}} ]] || [[ `diff _build/invoicer-location.nginx {{nginx_location_file_path}}` ]]; then
+    echo "deploying nginx location config"
+
+    if [[ -e {{nginx_location_file_path}} ]]; then
+        # Make a backup of the existing file.  This works because nginx only
+        # looks for ".conf" files.
+        today=`date +%Y-%m-%d-%H:%M:%S`
+        mv {{nginx_location_file_path}} {{nginx_location_file_path}}.$today
+    fi
+
+    cp _build/invoicer-location.nginx {{nginx_location_file_path}}
 
     $(nginx -t > /dev/null 2>&1)
     if [[ ! "$?" -eq 0 ]]; then
